CREATE DATABASE QUANLYTHUVIEN;

USE QUANLYTHUVIEN;

CREATE TABLE SACH (
    MASH INT PRIMARY KEY AUTO_INCREMENT,
    TENSACH VARCHAR(200),
    TACGIA VARCHAR(100),
    NHAXB VARCHAR(100),
    NAMXB INT
);

CREATE TABLE DOCGIA (
    MADG INT PRIMARY KEY AUTO_INCREMENT,
    HOTEN VARCHAR(100),
    NGAYSINH DATE,
    DIACHI VARCHAR(200),
    NGHENGHIEP VARCHAR(100)
);

CREATE TABLE PHIEUMUON (
    SOPM INT PRIMARY KEY AUTO_INCREMENT,
    NGAYMUON DATE,
    MADG INT,
    NGAYTRA DATE,
    CONSTRAINT fk_phieumuon_docgia FOREIGN KEY (MADG)
        REFERENCES DOCGIA(MADG) ON UPDATE CASCADE
);

CREATE TABLE CHITIETMUON (
    SOPM INT,
    MASH INT,
    PRIMARY KEY (SOPM, MASH),
    CONSTRAINT fk_chitietmuon_phieumuon FOREIGN KEY (SOPM)
        REFERENCES PHIEUMUON(SOPM) ON UPDATE CASCADE,
    CONSTRAINT fk_chitietmuon_sach FOREIGN KEY (MASH)
        REFERENCES SACH(MASH) ON UPDATE CASCADE
);
