CREATE DATABASE QUANLYLAODONG;

USE QUANLYLAODONG;

CREATE TABLE CONGTRINH (
    MACT INT PRIMARY KEY AUTO_INCREMENT,
    TENCT VARCHAR(100),
    DIADIEM VARCHAR(200),
    NGAYCAPGP DATE,
    NGAYKC DATE,
    NGAYHT DATE
);

CREATE TABLE PHONGBAN (
    MAPB INT PRIMARY KEY AUTO_INCREMENT,
    TENPB VARCHAR(100)
);

CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY AUTO_INCREMENT,
    HOTEN VARCHAR(100),
    NGAYSINH DATE,
    PHAI CHAR(1),
    DIACHI VARCHAR(200),
    MAPB INT,
    CONSTRAINT fk_nhanvien_phongban FOREIGN KEY (MAPB)
        REFERENCES PHONGBAN(MAPB) ON UPDATE CASCADE
);



CREATE TABLE PHANCONG (
    MACT INT,
    MANV INT,
    SLNGAYCONG INT,
    PRIMARY KEY (MACT, MANV),
    CONSTRAINT fk_phancong_congtrinh FOREIGN KEY (MACT)
        REFERENCES CONGTRINH(MACT) ON UPDATE CASCADE,
    CONSTRAINT fk_phancong_nhanvien FOREIGN KEY (MANV)
        REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE
);
