CREATE DATABASE QUANLYLICHDAYHOC;

USE QUANLYLICHDAYHOC;

CREATE TABLE GIAOVIEN (
    MAGV INT PRIMARY KEY AUTO_INCREMENT,
    HOTEN VARCHAR(100),
    DTGV VARCHAR(15)
);

CREATE TABLE MONHOC (
    MAMH INT PRIMARY KEY AUTO_INCREMENT,
    TENMH VARCHAR(100)
);

CREATE TABLE PHONGHOC (
    SOPHONG INT PRIMARY KEY AUTO_INCREMENT,
    CHUCNANG VARCHAR(100)
);

CREATE TABLE KHOA (
    MAKHOA INT PRIMARY KEY AUTO_INCREMENT,
    TENKHOA VARCHAR(100),
    DTKHOA VARCHAR(15)
);

CREATE TABLE LOP (
    MALOP INT PRIMARY KEY AUTO_INCREMENT,
    TENLOP VARCHAR(100),
    SISO INT,
    MAKHOA INT,
    CONSTRAINT fk_lop_khoa FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA) ON UPDATE CASCADE
);

CREATE TABLE LICHDAY (
    MAGV INT,
    MALOP INT,
    NGAYDAY DATE,
    BAIDAY VARCHAR(50),
    GHICHU VARCHAR(255),
    MAMH INT,
    SOPHONG INT,
    TUTIET INT,
    DENTIET INT,
    LYTHUYET INT,
    PRIMARY KEY (MAGV, MALOP, NGAYDAY, TUTIET),
    CONSTRAINT fk_lichday_giaovien FOREIGN KEY (MAGV)
        REFERENCES GIAOVIEN(MAGV) ON UPDATE CASCADE,
    CONSTRAINT fk_lichday_lop FOREIGN KEY (MALOP)
        REFERENCES LOP(MALOP) ON UPDATE CASCADE,
    CONSTRAINT fk_lichday_monhoc FOREIGN KEY (MAMH)
        REFERENCES MONHOC(MAMH) ON UPDATE CASCADE,
    CONSTRAINT fk_lichday_phonghoc FOREIGN KEY (SOPHONG)
        REFERENCES PHONGHOC(SOPHONG) ON UPDATE CASCADE
);
