CREATE DATABASE BANHANGDATABASE;

USE BANHANGDATABASE;

CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY AUTO_INCREMENT,
    TENKH VARCHAR(100),
    DIACHI VARCHAR(200),
    THANHPHO VARCHAR(100),
    DIENTHOAI VARCHAR(15)
);

CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY AUTO_INCREMENT,
    HONV VARCHAR(50),
    TENNV VARCHAR(50),
    GIOITINH CHAR(1),
    NGAYSINH DATE,
    DIACHI VARCHAR(200),
    DIENTHOAI VARCHAR(15)
);

CREATE TABLE LOAIHANG (
    MALOAI INT PRIMARY KEY AUTO_INCREMENT,
    TENLOAI VARCHAR(100)
);

CREATE TABLE MATHANG (
    MASP INT PRIMARY KEY AUTO_INCREMENT,
    MALOAI INT,
    TENSP VARCHAR(100),
    DONVITINH VARCHAR(50),
    DONGIA DECIMAL(10, 2),
    CONSTRAINT fk_mathang_loaihang FOREIGN KEY (MALOAI) 
        REFERENCES LOAIHANG(MALOAI) ON UPDATE CASCADE
);

CREATE TABLE HOADON (
    MAHD INT PRIMARY KEY AUTO_INCREMENT,
    MAKH INT,
    MANV INT,
    NGAYLAPHD DATE,
    NGAYNHANHANG DATE,
    CONSTRAINT fk_hoadon_khachhang FOREIGN KEY (MAKH) 
        REFERENCES KHACHHANG(MAKH) ON UPDATE CASCADE,
    CONSTRAINT fk_hoadon_nhanvien FOREIGN KEY (MANV) 
        REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE
);

CREATE TABLE HOADONHANG (
    MAHOADONHANG INT PRIMARY KEY AUTO_INCREMENT,
    MAHD INT,
    MASP INT,
    SOLUONG INT,
    CONSTRAINT fk_hoadonhang_hoadon FOREIGN KEY (MAHD) 
        REFERENCES HOADON(MAHD) ON UPDATE CASCADE,
    CONSTRAINT fk_hoadonhang_mathang FOREIGN KEY (MASP) 
        REFERENCES MATHANG(MASP) ON UPDATE CASCADE
);

